server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 2048GB
      max-request-size: 2048GB

  datasource:
    name: nddb
    url: jdbc:mysql://localhost:3306/nddb
    username: root
    password: yanjiyi0107
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 1
      max-wait-millis: 60000
      time-between-eviction-runs-millis: 60000
      validation-query: select 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      max-total: 20

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.suannai.netdisk.model